### PR TITLE
Implement `Disable()` on handler configurers.

### PR DESCRIPTION
**Pull request by jmalloc**
#### What change does this introduce?

This PR adds an `IsDisabled()` method to the `Handler` and `RichHandler` interfaces, the return value of which is driven by calls to the `Disable()` method on Dogma's handler configurer interfaces (`AggregateConfigurer`, etc).

#### Why make this change?

I wanted to prototype this before merging dogmatiq/dogma#162

#### Is there anything you are unsure about?

I haven't looked into adding support for `Disable()` to the static analysis system. ~I also haven't added support to the interopspec config API.~

#### What issues does this relate to?

- dogmatiq/dogma#162

### CODE REVIEW

**Comment by jmalloc** [comment]
Thinking some more about the static analysis side of things, I'm not sure we can even report the disabled status in any meaningful way, because `c.Disable()` would always be called conditionally (otherwise the handler would always do nothing).

**Comment by jmalloc** [comment]
After discussion with @danilvpetrov, we decided to change the `IsDisabled()` method to instead return an enum of `Enabled`, `Disabled` and `ConditionallyDisabled` allowing us to represent all three possibilities from static analysis.

When the config is constructed from an in-memory application the return value will always be either `Enabled` or `Disabled`.

**Comment by jmalloc** [comment]
I've updated this PR to exclude any handlers that are disabled and otherwise unconfigured (i.e. no identity or routes) from application configurations.

**Review by koden-km — APPROVED** [review]

**Review by danilvpetrov — APPROVED** [review]

**Pull request merged**
